### ISSUE TITLE
Dev reload problem?

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#440]
npm start

Use: JVx.mobile and demo with features user
Be sure that config.json contains username admin and password for admin -> means autologin with admin

Open Contacts (DB) with features user

Change something in source code -> Application reloads and the admin user is authenticated, but the Contacts screen is opened.
This screen isn't available for admin user and it's shown on client-side only.

The menu for admin user is correct.

**Comment by gimmixAT** [comment]
can't reproduce in `master` or `master_04_03_2024`. I always get redirected to home

**Comment by rjahn** [comment]
Maybe wrong test order?

1: config.json -> admin/admin
2: npm start
3: logout -> login with features user
4: change source code in reactUI to force browser reload

- browser reloads - admin user is automatically authenticated with correct menu, but last screen (Contacts (DB)) is still shown

**Comment by gimmixAT** [comment]
Thank you, this way I was able to reproduce it. I resolved it by redirecting to home if the username changes during a reload of the running application which happened in this scenario.

**Comment by rjahn** [comment]
This is not a good solution because it's possible that a different user is able to open the same screen. The question is why the screen is shown after re-authentication?

Thers's an exit and startup request.... 

Also the application is set to:
  <Mobile.preserveOnReload>false</Mobile.preserveOnReload>

via mobile.xml which means that every reload starts a new application and destroys the previous application. 
The server sends back the open screen(s) and the question is, why the "old" screen is still open.

So, there's a general problem which can't be solved by checking the username :)

**Comment by gimmixAT** [comment]
The check only happens after the the exit command has been sent. It is more so that if the react app reloads during development it remains on the same screen. 

The actual problem is that the exit apparently doesn't return a remove of the currently open screen and it remains in the recycled state of the react app since the `transferType` "partial" is used there. The route to home also takes care of that since it also removes all internally saved screens in react.

**Comment by rjahn** [comment]
exit is only an information for the server - not client relevant because startup triggers a new start on server-side.

transfertype means that the client handles work-screens and the application frame itself is on client-side.
We also have transfertype full which also handles the application frame itself.
There's a big difference between both modes, but handling the work-screen in partial mode is correct.

The user check is not enough, because it's possible that the user was reconfigured (theoretically) and is not allowed to use the screen after re-login. 

So, after reload the cache should be cleared if preserveOnReload is disabled?

If enabled? Nothing should be cleared because no re-login will be done...

**Comment by gimmixAT** [comment]
I changed the behavior a bit in fff92990a01407c6f7fb517164493d062256e38d and now if `preserveOnReload` is not enabled the active screens will be cleared and the browser redirected to /home regardless of the user.

**Comment by rjahn** [comment]
Ok, but I guess we still have a problem, because:

User A (Screen 1, 2, 3)
User B (Screen 1, 3)
User C (Screen 4)

If User C opens Screen 4 and reloads -> autologin User A -> no screen should be open

If User B opens Screen 1 and reloads -> autologin User A -> Screen 1 should be open?

**Comment by rjahn** [comment]
config.json - username: features
URL: http://localhost:3000/#/screens/Components

Change UICheckBox.tsx or other classes....
After UI reload, often re-linked to http://localhost:3000/#/home

or just press Browser Reload if URL is: http://localhost:3000/#/screens/Components

will be http://localhost:3000/#/home after reload.

It should be: http://localhost:3000/#/screens/Components

**Comment by gimmixAT** [comment]
I removed the redirect to home, now there is a security error dialog after reload because the admin user is not allowed to see the screen. I guess that is a somewhat better behavior than just redirecting to home.

**Comment by rjahn** [comment]
I guess, current navigation checks the navigation name of menu?
The URL /screens/Components needs a mapping with the classname of the work-screen?
The menu response contains a navigation name for this mapping?

So, if there's no mapping or if it's not possible to find a menu entry for the "URL", don't send an openScreen response and show home instead.

If you navigate to /screens/NoScreen - no error occurs, so I guess the current mapping has a problem with caching or navigationname to screen class?

After reload, the menu doesn't contain Components, so open screen shouldn't work - fine!
So why do we send open screen if the menu doesn't contain the screen? I guess because we know the screen class from previous calls?

**Comment by gimmixAT** [comment]
this should be fixed now -> the problem was that the map used to check against for where to route the user based on the path was kept around on reload as well.

**Comment by rjahn** [comment]
There's still a problem:

be sure to have features/features user in config.json -> autologin!

Logout and manually change to admin/admin -> Open the Simple screen (only this screen is available)
-> Press Browser Reload

- features User is logged in - 

-> Open Components screen
-> Press Browser Reload -> Home screen is shown instead of Components

This happens because browser URL doesn't contain the right navigation target after opening the Components screen!

**Comment by gimmixAT** [comment]
the described behavior, where the route in the addressbar isn't updated after switching user and reloading should be fixed now
