### ISSUE TITLE
login input field styles changes

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#472]
Login form before primereact update:

<img width="507" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/f06fe0e9-65e2-43ff-87d3-63f76711db9f">

after:

<img width="507" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/0d65ed5d-9c30-4235-ba07-ff0c3ca5a993">

Styles has changed in prime react:
'~primereact/resources/themes/saga-blue/theme.css';

Also we should use the new input label instead of inline labeling.

**Comment by gimmixAT** [comment]
should be fixed by c6a273ac2f80b7e5f8943d8d29fc98ac08d975fc

**Comment by rjahn** [comment]
It's not fixed... it's different.
We could use FloatLabel component which should work with primereact 10.6.4?

Current login looks:

<img width="433" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/d01d93d6-b58e-472d-856c-a18392f159dd">

The prompt should be inside as long as there's no focus and should move outside/top when focus received...

**Comment by gimmixAT** [comment]
If the label is inside the field that would result in big gaps in-between the fields as mentioned https://github.com/sibvisions/reactUI/issues/472#issuecomment-2096127594

**Comment by gimmixAT** [comment]
login form uses the new float label now
