### ISSUE TITLE
Table performance problem

### ISSUE THREAD

**Issue by rjahn** [sibvisions/reactUI#486]
Lazy loading screen

If we enable search (via toolbar) -> a search row will appear.

1. Problem

Fetch all records from server

-> client receives a dataProviderChanged from server via button click -> reload: -1 is set 
This means: clear data cache for data provider and load data again, but don't send rowCount: -1 which means -> fetch all records

There's something wrong with fetch

2. Problem

every row selection change will send selectRow to server and server will send a response with many empty cell formats because there is only a cell format for first record.

Will it work if we remove trailing empty cell formats from response? Not sure if client can handle it if number of records dont' match with number of client records?

**Comment by gimmixAT** [comment]
Regarding 1. is there a button to trigger this (if yes where?) or do I have to scroll all the way to the end?

Regarding 2. the UITable should be able to handle undefined cellformats. Any kind of index mismatch might cause some issues down the line though but trailing shouldn't be an issue.

**Comment by rjahn** [comment]
The magnify button beside the table:

<img width="443" alt="image" src="https://github.com/sibvisions/reactUI/assets/1307043/83197702-ad37-4659-a2cc-338ce0d0ff1d">

Regarding 2: will try it

**Comment by gimmixAT** [comment]
Regarding 1. I removed the `rowCount: -1` from the reload request and toggling search is now, as expected, way quicker

**Comment by rjahn** [comment]
some flickering?
I guess the calculation of column width is "always" ? The column width calculation should only happen in case of first fetch and first re-fetch.

https://github.com/sibvisions/reactUI/assets/1307043/134e6bb2-f2e2-4dc5-913f-e731d0263bf7

**Comment by gimmixAT** [comment]
We already used to override PR DataTables Columnwidths but apparently they started to more aggressively replace the DOM. I added an effect to reapply our widths as soon as the ref changes: 3e31551ef1646adc4f06a80e9bdaab7626a8232b

**Comment by rjahn** [comment]
With current master, lazy loading screen doesn't work because records are not shown correctly.
The table shows a white area behind last record and loads e.g. 98 records, but not more...

See:

https://github.com/sibvisions/reactUI/assets/1307043/08056e5b-5db4-4b36-826f-074107f9431e

**Comment by gimmixAT** [comment]
I can't reproduce the table stopping loading data in either FF or Chrome on Windows i.e. it works for me. Maybe this is a safari / macos problem?

**Comment by rjahn** [comment]
I can't reproduce stop loading on my system today.... but loading doesn't work as expected. Scroll slowly to reproduce the problem. The table is loading data too late and shows an empty area (with or without formatting).

https://github.com/sibvisions/reactUI/assets/1307043/2a156eff-9db3-4d16-9eb9-5e2dfd41aac4


https://github.com/sibvisions/reactUI/assets/1307043/76156707-045a-48d1-8d71-0f1806f81546

**Comment by gimmixAT** [comment]
@rjahn  I can't reproduce this in Safari. Can you maybe check what version of primereact you have installed via `npm ls`. I currently have 10.7.0

**Comment by rjahn** [comment]
My version was: primereact@10.6.6

**Comment by rjahn** [comment]
Works great in Chrome, but with Safari and primereact 10.8.2 it doesn't work better with Safari:

https://github.com/user-attachments/assets/285112ed-d281-452a-a1ed-ffe74eb48ff2

**Comment by gimmixAT** [comment]
@rjahn can you still reproduce this? in Safari 18 with primereact 10.18.4 I can't get it to leave this empty gap at the end of the list

**Comment by rjahn** [comment]
Currently it works better than ever before.
Tested in FF, Chrome and Safari

There are still some problem:

Open incognito browser (FF or Chrome), use URL: http://localhost:3000/#/screens/LazyLoading (manual login is required in my case)

After login, the lazy loading screen is open and try to scroll down:

https://github.com/user-attachments/assets/c2d57e51-fdf3-4aa9-80f2-4fdd163bf082



White space problem in FF incognito mode:

Scroll down slowly... there's some white space behind last shown record... continue scrolling and records will appear. It's not a problem with fetching records, records are not painted?

https://github.com/user-attachments/assets/b59eaad7-286a-4fe9-b3ba-994e6dc0a6bd


If you scroll down very fast, the problem is not so often.

**Comment by rjahn** [comment]
Do you have an update for this problem because not painted or not shown records are a big problem.

**Comment by gimmixAT** [comment]
I just pushed a change that might fix this. The problem seems to have been, that primereact's virtualscroller doesn't update the viewport information after the first render unless we force it by changing around some unused props.

**Comment by rjahn** [comment]
First test with FF and incognito mode:

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/881917b7-ed29-492e-a573-8713b1badbd9" />

Scroll down slowly... white area is gone but records are "empty". Continue testing with other browsers.

**Comment by rjahn** [comment]
same with Safari:

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/19a95509-ca17-4a73-902a-a5a6d62996a7" />

**Comment by rjahn** [comment]
Additional records are not clickable, means no selection possible.

**Comment by gimmixAT** [comment]
the empty rows should be fixed now

**Comment by rjahn** [comment]
Much better, but sometimes it still happens:

<img width="1571" alt="image" src="https://github.com/user-attachments/assets/e674b059-1d99-4249-9da4-be0b9129d624" />

Tested with FF.

or Safari:

<img width="1571" alt="image" src="https://github.com/user-attachments/assets/86c8e594-7be8-46a1-bb1f-15b9f722126e" />

Chrome was too fast and I wasn't able to reproduce it. But I guess the problem is still there, but Chrome renders faster or sends additional events?


And another problem is now: Scroll down to e.g. record 600 (fast) and open the Lazy Loading screen again (click menu item). This request loads ALL records and takes longer than usual.

Reproducable in Chrome, FF, Safari

**Comment by gimmixAT** [comment]
The loading of all the rows should be fixed now.

The blank rows might still happen if that data is still loading, but I fixed an issue where rows went blank after they already had data in them.

**Comment by rjahn** [comment]
Now there are no records in the table if I open the LazyLoading screen again.

There's a fetch request, with valid response, but no records are shown:

<img width="1571" alt="image" src="https://github.com/user-attachments/assets/8e128b3b-4ba8-4d15-a109-c344bd2f3483" />

macOS, Chrome

**Comment by gimmixAT** [comment]
This should work again as well. When reopening the same screen the information about the databook got lost or was removed because of closing the screen and then added too late when reopening it for the rendering to make use of it. I readded the behavior of the hook that I removed which basically ignores that a databook isn't known about and sends the fetch request to the server anyway -> 27ed850d164e6b17071a2ffea22e574175324884

**Comment by rjahn** [comment]
Current solution works better than every solution before. It was not possible to reproduce the problem(s), so it's done. If some empty lines will happen, I'll open a new issue.
